include_guard(GLOBAL)

if(NOT WIN32 AND PROJECT_IS_TOP_LEVEL)
  set(CMAKE_INSTALL_PREFIX "/opt/AetherRadio")
  set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
endif()

set(AETHER_X6100CTRL_INSTALL_PLUGINDIR ${CMAKE_INSTALL_BINDIR}/plugins)
